# Generated by Django 4.1.5 on 2023-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_department_author_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='authorName',
        ),
    ]
