# Generated by Django 4.1.5 on 2023-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_name_author_authorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorName',
            new_name='name',
        ),
    ]
