# Generated by Django 4.1.5 on 2023-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_authorname_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='date_ceated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
