# Generated by Django 4.1.5 on 2023-02-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contactmessage_date_ceated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='date_ceated',
            new_name='date_created',
        ),
    ]
