# Generated by Django 4.1.5 on 2023-02-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_applicationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='ApplicationFormModel',
        ),
    ]
