# Generated by Django 4.1.5 on 2023-02-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_applicationform_applicationformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='nationalIdOrPassport',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
