# Generated by Django 4.1.5 on 2023-02-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_date_ceated_contactmessage_date_created'),
        ('website', '0014_alter_applicationformmodel_cv_and_more'),
    ]

    operations = [
    ]
