# Generated by Django 4.1.5 on 2023-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_merge_20230227_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='nationalIdOrPassport',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='refereeAddress',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='refereeInstitution',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='refereeName',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='refereeOccupation',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='refereeTelephone',
        ),
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='workCertificate',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='date_created',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_ceated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
