# Generated by Django 4.1.5 on 2023-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_applicationformmodel_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformmodel',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
