# Generated by Django 4.1.5 on 2023-02-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_applicationformmodel_cv_applicationformmodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='gender',
        ),
    ]
