# Generated by Django 4.1.5 on 2023-02-27 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_applicationformmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformmodel',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='cv',
            field=models.FileField(upload_to='application/applicationImages'),
        ),
    ]
