# Generated by Django 4.1.5 on 2023-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_applicationformmodel_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='cv',
            field=models.FileField(null=True, upload_to='application/applicationImages'),
        ),
    ]
