# Generated by Django 4.1.5 on 2023-02-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_applicationformmodel_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='gender',
        ),
    ]
