# Generated by Django 4.1.5 on 2023-02-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_applicationformmodel_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationformmodel',
            old_name='dob',
            new_name='dateOfBirth',
        ),
    ]
