# Generated by Django 4.1.5 on 2023-02-27 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_applicationformmodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformmodel',
            name='refereeAddress',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='refereeInstitution',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='refereeName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='refereeOccupation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='refereeTelephone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
