# Generated by Django 4.1.5 on 2023-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_applicationformmodel_refereeaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
